findRoots:
  cPolyMat_determinant:
    sym_matrix_det:
      method: berkowitz

  cPolyVal_findRoots:
    nw_rootsSym:
      symPoly_nroots:
        n: dps # use mpmath dps. Specify a value to override.
        maxsteps: 500
        cleanup: True

findPoles:
  stelempy:
    startingDistThres: 0.0001
    endDistThres: null
    cfSteps: 2
    amalgThres: null

fitCharts:
  colourCycle:
    - green
    - red
    - blue
  xsize: 8
  ysize: 7
