find_Fin_roots:
  cMatSympypoly_determinant:
    sym_matrix_det:
      method: berkowitz

  cScaSympypoly_find_roots:
    nw_roots_sym:
      symPoly_nroots:
        n: dps # use mpmath dps. Specify a value to override.
        maxsteps: 5000
        cleanup: True

find_stable_Smat_poles:
  zero_filt_thres:
    point: 0.
    atol: 0.001+0.001j
  stelempy:
    start_rtol: 0.0001
    end_rtol: 1e-20
    ztol: 1e-7
    cfsteps: 3
    amalg_rtol: 0.0001

fit_charts:
  colour_cycle:
    - purple
    - green
    - orange
  xsize: 8
  ysize: 7

create_formatted_QI_tables:
  num_format:
    strip_zeros: False
    min_fixed: -3
    max_fixed: 3
    show_zero_exponent: False
    ztol : 1e-20
