find_Fin_roots:
  cMatSympypoly_determinant:
    sym_matrix_det:
      method: berkowitz
  cScaSympypoly_find_roots:
    nw_roots_sym:
      force_nroots: True
      symPoly_nroots:
        n: dps # use mpmath dps. Specify a value to override.
        maxsteps: 5000
        cleanup: True

find_stable_Smat_poles:
  root_filt:
    point: 0.0271
    atol: 0.001+0.001j
  stelempy:
    start_rtol: 0.0001
    end_rtol: null
    ztol: 1e-7
    cfsteps: 3
    amalg_rtol: 0.0001

fit_charts:
  colour_cycle:
    - green
    - red
    - blue
  dashes: [null, [[3,2]]]
  cycle_dashes: True
  hide_title: False
  show: True
  xsize: 8
  ysize: 7
  dpi: 1200
  extension: "png"

create_formatted_QI_tables:
  num_format:
    strip_zeros: False
    min_fixed: -3
    max_fixed: 3
    show_zero_exponent: False
    ztol : 1e-20
  conversion_dps_mod: 0
